package com.example.EnglishMeApp;

import android.content.Context;
import android.database.DatabaseErrorHandler;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.provider.BaseColumns;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

/**
 * Created by GudovanyiAlexey on 14.01.2016.
 */
public class DatabaseHelper extends SQLiteOpenHelper implements BaseColumns {
    private static final String DATABASE_NAME = "englishme.db";
    private static final int DATABASE_VERSION = 1;
    public static final String KEY_ROWID = "_id";
    private static final String CLIENT_TABLE = "clients";
    private static final String PAYMENTS_TABLE = "payments";
    public static final String NAME_COLUMN = "name";
    public static final String PHONE_COLUMN = "phone";
    public static final String DATE_COLUMN = "date";
    public static final String CLIENT_ID_COLUMN = "client_id";
    private static final String CREATE_CLIENTS_TABLE = "create table "
            + CLIENT_TABLE + " (" + BaseColumns._ID
            + " integer primary key autoincrement, " + NAME_COLUMN
            + " text not null, " + PHONE_COLUMN + " text);";
    private static final String CREATE_PAYMENTS_TABLE = "create table "
            + PAYMENTS_TABLE + " (" + BaseColumns._ID
            + " integer primary key autoincrement, " + CLIENT_ID_COLUMN
            + " integer not null, " + DATE_COLUMN + " text);";

    public DatabaseHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    public DatabaseHelper(Context context, String name, SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    public DatabaseHelper(Context context, String name, SQLiteDatabase.CursorFactory factory, int version, DatabaseErrorHandler errorHandler) {
        super(context, name, factory, version, errorHandler);
    }

    @Override
    public void onCreate(SQLiteDatabase sqLiteDatabase) {
        //Create Tables
        sqLiteDatabase.execSQL(CREATE_CLIENTS_TABLE);
        sqLiteDatabase.execSQL(CREATE_PAYMENTS_TABLE);

        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Рябошапка Лиза Константиновна',0678646414);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Вивдич Юлия Васильевна',0675004806);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Косташ Уляна Андреевна',0637673021);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Иванова Настя',0675969744);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Леон Инна',0976985615);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Гончар Анна Викторовна',0672441312);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Полторацкий Саша',0673788760);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Корниенко Таня',0964708563);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Терещенко Ирина',0674422634);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ситниченко Диана',0937554466);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Повар Даня',0672206512);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Богуш-Заднепрянская Настя',0674478526);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Днепровская Евгения Владимировна',0503488572);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Бованенко Наталья',0505939939);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Горбачева Анастасия (Костя)',0978158685);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Сенченко Виталий',0679989018);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Бондаренко Костя',0977517020);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Акилычев Дима',0671123884);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Провотар Инна',0977178605);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Проценко Александра',0984802413);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Бурлаченко Дарья Александровна',0938072125);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Сущенко Данило',0672920892);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Корягин Александр',0672330406);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Текина Настя',0623923700);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Волобуев Алексей Александрович',0666756222);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Дашивец Александр',0933313331);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шестакова Анна',0962055871);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Куприенко Саша',0671456407);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Веремиенко Александр',0930201955);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Колониари Настя',0675076913);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Яковчук Ольга',0505043085);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Гужова Аня',0632819772);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Гавриш Александра',0672981133);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Бакеев Матвей',0505836237);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Зень Ярослав Богданович',0675050015);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Гниленко Мария',0936490888);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Жирнова Анна Викторовна',0952804840);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Устинов Игорь Викторович',0673212331);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Левченко Рома',0934953499);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Орехова Светлана Анатолиевна',0937510015);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кушнерук Аня',0509611155);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Чевкота Елена Александровна',0661177516);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кондратевич Таня',0934730258);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Тимофей Малмыгин',0503116824);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Бакеева Саша',0505836237);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Корниенко Лиза',0964708563);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Коломиец Настя Сергеевна',0635793245);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ермоленко Елена Анатольевна',0968188750);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Подлесная Юлия',0679691592);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Пащинский Володимир',0);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Александрович Александра',0507506033);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Паламаренко Юлия Валентиновна',0676911973);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Винничук Ольга',0953634824);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кормуш Полина',0672174277);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Тур Настя Романовна',0672737649);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Жирун Ярослав',0679856039);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Остракова Тамара',0678890909);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Щуренко Павел',0674457515);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Морозов Марьян',0988362563);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Сидоренко Надя',0507431214);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шатковский Никита',0957593301);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кулагин Максим Олегович',0668394821);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шашенко Даня',0674427270);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ерашов Кирилл',0637337760);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Матвиенко Полина',0506878345);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Миклуха Катя',0979412975);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Федчишин Артем',0505746797);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Артеменко Дмитрий',0679663372);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Лахтуров Богдан',0974673094);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Черненко Марина',0952879252);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шевченко Ольга Ивановна',0688107628);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ребрий Никита',0674478282);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Косенко Наталья (Лена)',0507620505);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ясинский Владислав Викторович',0971724090);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Лихицкая Лера',0935707800);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Заболотная Елена Ивановна (Наташа)',0503558332);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Юхновец  Денис',0676760660);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Братусь Ира',0974279709);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Боярчук Ира',0984153331);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Остраков Алексей',0678890909);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Нестеренко Аня',0934139084);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Дейнеко Виктория',0503183034);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Филипенко Рита',0950126854);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Слезкина Даша',0630759591);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кудь Таня',0934864377);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шумилина Галина Романовна',0672455775);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Пижук Саша',0507275127);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ярмыш Алена',0951888843);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Розвосовский Александр',0636096996);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Бейдер Нюся',0672164251);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шимко Оля',0663892207);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кравцов Евгений',0445920167);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кузьмищенко Константин',0503242433);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Баранов Олег',0676409310);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Косташ Катя',0636329707);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Радченко Светлана',0938271993);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Сагань Юлия',0673681218);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Павлова Елена Юрьевна',0503529674);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ковгановская Наташа',0443619141);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Сикалюк Людмила',0636317114);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Тонконоженко Аня',0979725443);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кравченко Максим',0634615275);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кушнирчук Настя',0661885027);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Громова Дарья',0);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Метоль Вадим',0939199921);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Борисенко Александр',0674092702);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Крисан Вика',0930211738);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Куликовский Ярослав',0679894352);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Редкач Богдан',0509873141);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Мазницька Лада',0677571889);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Голубчик Аня',0679832713);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шматко Алена',0677654180);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Настя',0503911539);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Каплун Андрей',0979376180);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Сорокин Кирилл',0683070524);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Бобкова Аня',0951004060);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Аня (5 кл)',0951620298);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Таня',0667746485);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Алина',0989011964);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Игнатьев Алексей',0505001321);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Елена',0672150130);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Иващенко Оксана Алексеевна',0970251361);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шматко Наташа',0677654180);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Андрей Симагин (3 кл)',0672329715);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Женьчак Марина',0678244046);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Настя',0632811610);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Маша',0507175888);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Юля Компанией',0504742442);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Елена (спикинг клаб)',0660724868);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ольга (Тоефл интермед)',0667828081);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Виктория',0503183034);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Оксана 5 кл 11 лет',0936803536);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Дарья 5 лет Наталия',0672386726);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Тамара Апер Интрем',0683274644);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Александр',0503398944);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Екатерина Лит клуб',0965711716);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Нила Елементари',0504154624);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Наталия Елементари дневное время',0996092922);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Эрика 3 кл 9 лет',0637137787);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Татьяна 3 кл Экселент',0504427809);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Заброда Илья',0954862898);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Клюс Яна',0978477127);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Маршалюк Анастасия Дмитриевна',0672238045);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Овчинникова Саша',0667463263);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Константинова Богдана',0959200009);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Гребенюк Светлана Васильевна',0990705989);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ильина Елена Алексеевна',0504186124);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Пазюк Маргарита Сергеевна',0963371563);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Маначинская София',0935305780);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Горошко Светлана Александровна',0630541563);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Спивак Татьяна',0633797678);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Рак Катерина Георгиевна',4405230);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кмецинская Анастасия Александровна',0935130604);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Олифира Алина Андреевна',0932771027);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Цвилык Алена Александровна',0636217111);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Даниленко Лилия Андреевна',0971640008);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Даниленко Мария Андреевна',0972081514);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Бородай Григорий',0503580171);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кирий Анна',0673779773);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Дуброва Оксана Николаевна',0950744434);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Карпенко Анна Сергеевна',0937631235);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Дрейзер Сергей Сергеевич',0935905559);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Скрупский Филипп Викторович',0955457857);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ясинская Вика',0976634767);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Красникова Анна Сергеевна',0935238834);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Субботина Анюта',0677066490);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Осауленко Ангелина Виталиевна',0678102574);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Крамар Даниил',0503810076);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кушнирчук Павел Михайлович',0662531047);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Мокосий Татьяна Александровна',0971760832);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Павлова Елена Николаевна',0995451845);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Клименко Ольга Алексеевна',0672202446);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Матвиенко Ирина Александровна',0933231495);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Чередникова Дарья',0976581615);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Пашинська Неонила Григорівна',0504154624);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Гидзиль Катя',0673035921);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Седых Анастасия Алексеевна',0505977832);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Сирица Егор Олегович',0506934383);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Костырин Сергей',0672641111);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Чевкота Сергей',0667677441);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Коваленко Александр Владимирович',0674442445);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кушнерчук Настя Павловна',0);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Белок Александр Владимирович',0631146895);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Городников Игорь Олегович',0508577619);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Воробьева Яна Сергеевна',0502650498);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Опрышко Роман Валентинович',0939929977);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Гречко Камилла Олеговна',0501300242);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Волобоев Олег',0955959570);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Юневичус Арина',0975690732);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Курячий Виктор Викторович',0954430373);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Компанец Юлия Романовна',0960778808);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Овчарова Наталия',0508386121);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Васильева Валентина Сергеевна',0962707580);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Быстрова Екатерина Владимировна',0501909020);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Старикова Вероника Александровна',0955669990);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Щербак Кирилл',0955107789);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Тесленко Артем',0509137430);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Безсмертный Тимофей',0963781645);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Бованенко Саша',0505939939);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Бычков Миша',0957191690);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шматко Олег',0677654180);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Сагань Денис',0672142263);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Макущенко Маша',0679142560);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Лавренчук Денис',0973420303);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Александрин Игорь',0967143888);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Дордочкин Иван',0994915712);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Фурман Илья',0507119103);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Степаненко Артем',0664150512);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Слобоженко Дима',0960933164);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Юрченко Виталия',0);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Войтенко Катя',0633783307);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Дрозденко Женя',0687219467);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Парвенко Карина',0664282353);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Макущенко Леша',0675857324);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Левченко Миша',0957696656);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Мишковец  Лева',0502057555);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Коновалова  Настя',0675051640);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Винничук Надя',0953634824);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Гульчинская Елизавета',0966690169);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Голубчик Даша',0679832713);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Оникиенко Ростик',0936068989);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Макитрук Даша',0996092922);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Радостин Кирилл',0666170998);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Хижа Вера',0991614615);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Литвиненко Арсений',0954167197);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Руднев Женя',0676841743);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Лавренчук Юля',0973420303);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Цицилиано Денис',0979828861);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Аврамич Лиза',0675063303);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Полонская Маша',0675617679);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('София',0);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Вероника',0675967566);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Романенко Даша',0952833621);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Мирецкая Аглая',0507018427);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Андриянова Маша',0993750285);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Акимов Сергей',0630751013);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Иващенко Оксана Алексеевна',0953125237);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ячная София',0666797100);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Демчук Игорь Михайлович',0939464615);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кущ Денис Петрович',0508421072);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ладанюк Неля Анатолиевна',0508421072);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Маменко Валерия Александровна',0503804762);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Рябчий Мия Георгиевна',0);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Мельник Климент Романович',0688070461);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Чигир Елена Владимировна',0663311662);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Мовчанська Альвина',0957007658);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Власюк Анна',0972992001);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Вивдич Юлия',0675004806);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Рудяк Карина',0679203300);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Бордуленко Мария',0675967566);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Гудыменко Ирина Владимировна',0997380112);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Пчелинцева Адриана',0937696996);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Гаврилюк Митя',0932536816);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Сергей 2',0933500130);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ячная София',0);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Горбалюк Саша',0955027994);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Гуров Николай',0504125735);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Сорочан Аня',0985581122);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Захар',0962233342);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Топало Александр',0674279090);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Терешкова Наталия',0935253646);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Крюк  Сергей Александрович',0672401659);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Смалийчук Светлана Леонидовна',0636146356);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Смалийчук Олег Павлович',0930555400);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Егорова Кира Викторовна',0663161186);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Корнеева Мария Алексеевна',0679967093);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шатерник Ольга Николаевна',0505466827);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Игумнова Елена Александровна',0507862648);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Корякова Марина Павловна',0675490019);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Трейтяк Марина Михайловна',0634190732);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Богданчик',0673078866);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Атаманчук Юлиана',0);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шевчик Даня',0504133044);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Голубчик Назар',0504622716);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Косовцова Маша',0503322118);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Петренко Аня',0984554111);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Лида',0663855573);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Водолазский Степан',0673214771);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Костырина Полина',0672641111);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Опанасенко Дима',0);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шевчук Даша и Даня',0505928390);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Зима Глеб',0664006460);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ульченко Максим',0663832436);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Середа Маша',0990054490);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Денисова Диана',0955946422);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Чечель Алена',0675813344);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Грицык Лера',0672465557);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Собченко Дима',0674251323);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шульга Евгений',0673931067);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Севертока Алексей',0509075539);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Вакуленко Сергей Анатольевич',0683897149);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Соколенко Сергей Николаевич',0979464615);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Пособчук Валерия Владимировна',0956615092);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Пособчук Ирина Руслановна',0956615092);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Яцко Юрий',0673903306);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Золотых Светлана',0978171351);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Борисенко Александр',0674092702);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Иванова Алена',0675969744);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Косташ Уляна',0637673021);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кушнерук София',0509611155);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Тригуб Миша',0505088851);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Радостин Кирилл',0666170998);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Олийник Настя',0676746619);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Гульчинская Елизавета',0966690169);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Антипов Иван',0936442401);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Шимко Ольга',0503567714);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Стадник Ярослав',0508535494);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Кравец Марьян',0505724231);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Тырса Настя',0679638774);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Мащенко Елена',0672150130);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Оксана',0970251361);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ямпольская Анастасия',0999716676);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ямпольский Александр',0999716676);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Скрупский Филипп',0955457857);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Грищенко Лиза',0965875000);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Константинов Артем',0664150512);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Ковалев Костя',0952744782);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Александра',0984082621);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Анатолий Зацаринный',0980061106);");
        sqLiteDatabase.execSQL("INSERT INTO clients (name, phone) values('Устименко Вова',0677619984);");
    }

    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int i, int i1) {

    }
}
